### PR TITLE
Windows

### PR DESCRIPTION
**Pull request by ananaphasia**
Got this running and working on windows. zip in /dist. Maybe you could keep this as a separate branch? Up to you. 

Thank you so much for making this!

### CODE REVIEW

**Comment by ananaphasia** [comment]
Added the .zip in /download/windows, and the .exe is in /dist.

**Comment by ananaphasia** [comment]
The last two commits are that I got the venv to work properly, instead of faking it by disabling it lol

**Review by chialunwu — APPROVED** [review]
Thank you for supporting Windows @ananaphasia ! 💪  🚀

**Comment by chialunwu** [comment]
Screenshot 2024-05-13 at 10 56 22

**Pull request merged**
